# ============================================================
# DISCOVERY SERVER - EUREKA
# ============================================================

# Nom de l'application
spring.application.name=discovery-server

# Port Eureka
server.port=8761


# ============================================================
# EUREKA SERVER
# ============================================================

# Le Discovery Server ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false

# Le Discovery Server ne récupère pas son propre registre
eureka.client.fetch-registry=false

# Activer le mode de conservation des instances
eureka.server.enable-self-preservation=true