# ============================================================
# API GATEWAY
# ============================================================

spring.application.name=api-gateway
server.port=8088


# ============================================================
# EUREKA
# ============================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=localhost:${spring.application.name}:${server.port}


# ============================================================
# SPRING CLOUD GATEWAY - WEBFLUX
# ============================================================

spring.cloud.gateway.server.webflux.enabled=true


# ============================================================
# DISCOVERY LOCATOR
# ============================================================

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# ============================================================
# USER SERVICE - AUTH
# ============================================================

spring.cloud.gateway.server.webflux.routes[0].id=user-service-auth

spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**


# ============================================================
# USER SERVICE - USERS
# ============================================================

spring.cloud.gateway.server.webflux.routes[1].id=user-service-users

spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**


# ============================================================
# CV SERVICE
# ============================================================

spring.cloud.gateway.server.webflux.routes[2].id=cv-service

spring.cloud.gateway.server.webflux.routes[2].uri=lb://cv-service

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/cvs/**


# ============================================================
# LOGGING
# ============================================================

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.reactor.netty.http.client=DEBUG